export const architectureLayers = [
  {
    tag: 'CRYPTO CORE',
    title: 'Circuit Noir',
    description:
      'The mathematical core. Takes investor private data, verifies 8 constraints (identity, country, type, limits), and produces a ~2KB proof. Lives entirely in the browser — no blockchain dependency.',
    chips: ['Noir', 'UltraPlonk', 'bn254'],
    color: 'emerald' as const,
  },
  {
    tag: 'ON-CHAIN',
    title: 'Smart Contracts',
    description:
      'Three Solidity contracts: ZKToken.sol (ERC-1400 security token), Registry.sol (Merkle root storage), and UltraVerifier.sol (generated by Noir). They only see hashes — zero personal data.',
    chips: ['Solidity', 'ERC-1400', 'Foundry'],
    color: 'violet' as const,
  },
  {
    tag: 'BROWSER',
    title: 'Frontend React',
    description:
      'Two interfaces: bank admin (KYC approval) and investor (transfer with proof). The proof is generated entirely in the browser via noir_js in WebAssembly.',
    chips: ['React', 'noir_js', 'ethers'],
    color: 'blue' as const,
  },
  {
    tag: 'GLUE',
    title: 'JS Integration',
    description:
      'The critical glue: circomlibjs for Poseidon hashing, MerkleTree class, string-to-Field conversion, Noir input preparation, and Solidity encoding.',
    chips: ['circomlibjs', 'TypeScript'],
    color: 'amber' as const,
  },
  {
    tag: 'CROSS-CHAIN',
    title: 'Alephium Integration',
    description:
      'Multi-chain extension via Wormhole bridge (V1) and an oracle attestation system in Ralph (V2). Alephium provides an energy-efficient PoW L1 with 8s block time and first-class tokens.',
    chips: ['Ralph', 'Alphred VM', 'Wormhole Bridge'],
    color: 'rose' as const,
  },
];

export const architectureCallout = {
  type: 'info' as const,
  title: 'The fundamental principle',
  text: 'In a traditional system (ERC-3643), the registry of approved investors is public on-chain. Keter replaces this registry with a single 32-byte hash (the Merkle root). To transfer, the investor mathematically proves they are in the registry without revealing who they are.',
};

export const architectureStats = [
  { value: '8', unit: 'constraints', label: 'In the circuit' },
  { value: '32', unit: 'bytes', label: 'Total on-chain' },
  { value: '~2', unit: 'KB', label: 'Proof size' },
  { value: '27', unit: 'countries', label: 'EU authorized' },
];
