export const contractDescriptions = [
  {
    name: 'KeterToken.sol',
    color: 'violet' as const,
    description:
      'The main contract. ERC-1400 security token with transferWithProof(). Manages balances, partitions, nullifiers, and legal documents.',
    features: [
      'Calls HonkVerifier for ZK verification',
      'Reads the root from Registry',
      'Stores used nullifiers (anti-replay)',
      'Supports pause/unpause by the issuer',
      'issue() to mint tokens with data partition',
    ],
  },
  {
    name: 'Registry.sol',
    color: 'emerald' as const,
    description:
      'Stores the Merkle root — the link between the off-chain world (investor tree) and the on-chain world. Only the admin can update it.',
    features: [
      'setMerkleRoot(bytes32) — admin only',
      'getMerkleRoot() — read by KeterToken',
      'Separable: reusable by multiple tokens',
      'Emits MerkleRootUpdated event',
    ],
  },
];

export const transferWithProofCode = `function transferWithProof(
    address to,
    uint256 amount,
    bytes calldata proof,
    bytes32[] calldata publicInputs
) external whenNotPaused {
    // 1. Valid Merkle root
    require(
        bytes32(publicInputs[0]) == registry.getMerkleRoot(),
        "KT: root mismatch"
    );

    // 2. Nullifier — anti-replay
    bytes32 nullifier = bytes32(publicInputs[1]);
    require(!usedNullifiers[nullifier], "KT: nullifier used");
    usedNullifiers[nullifier] = true;

    // 3. Recipient binding
    require(
        uint256(publicInputs[2]) == uint256(uint160(to)),
        "KT: recipient mismatch"
    );

    // 4. Sender binding
    require(
        uint256(publicInputs[3]) == uint256(uint160(msg.sender)),
        "KT: sender mismatch"
    );

    // 5. Amount binding
    require(
        uint256(publicInputs[4]) <= amount,
        "KT: transfer amount"
    );

    // 6. ZK PROOF VERIFICATION (~300k gas)
    require(verifier.verify(proof, publicInputs), "KT: invalid proof");

    // 7. ERC-20 Transfer
    _transfer(msg.sender, to, amount);
}`;

export const deploymentSteps = [
  {
    step: '01',
    title: 'HonkVerifier',
    description: 'Generated by nargo codegen-verifier. No dependencies.',
    tech: 'forge create',
    actor: 'Contract' as const,
  },
  {
    step: '02',
    title: 'Registry',
    description: 'Constructor: admin address (the bank).',
    tech: 'forge create',
    actor: 'Contract' as const,
  },
  {
    step: '03',
    title: 'KeterToken',
    description: 'Constructor: verifier + registry + issuer addresses.',
    tech: 'forge create',
    actor: 'Contract' as const,
  },
  {
    step: '04',
    title: 'Update root',
    description: 'The bank publishes the first Merkle root.',
    tech: 'cast send',
    actor: 'Bank' as const,
  },
  {
    step: '05',
    title: 'Issue',
    description: 'The issuer issues security tokens to investors.',
    tech: 'cast send',
    actor: 'Bank' as const,
  },
];

export const contractsCallout = {
  type: 'success' as const,
  title: 'Gas optimization',
  text: 'Cheap require() checks (~8k gas total) run before verifier.verify() (~300k gas). If any check fails, the transaction reverts before paying for verification — saving 97% of gas on errors.',
};
