export const erc1400Cards = [
  {
    tag: 'PARTITIONS',
    title: 'Segmented tokens',
    description:
      'DEFAULT (free), LOCKED (vesting), RESTRICTED (qualified-only). Each partition has its own transfer rules. An investor can hold tokens in multiple partitions.',
    color: 'violet' as const,
  },
  {
    tag: 'REGULATOR',
    title: 'Forced transfers',
    description:
      'The controller can force a transfer, freeze an account, or reclaim tokens — without a ZK proof. MiCA obligation. Actions are logged with specific events.',
    color: 'rose' as const,
  },
  {
    tag: 'DOCUMENTS',
    title: 'Legal on-chain',
    description:
      'Prospectus, regulations, terms: URI + hash stored on-chain. Integrity verification: if the document changes, the hash no longer matches.',
    color: 'emerald' as const,
  },
  {
    tag: 'OPERATORS',
    title: 'Delegation',
    description:
      'An authorized broker or custodian can submit transactions on behalf of the investor. The proof is generated by the investor — the operator only relays it.',
    color: 'amber' as const,
  },
];
