// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title UltraVerifier (Mock)
 * @notice Mock verifier that always returns true.
 *         Replace with the real UltraVerifier.sol generated by `nargo codegen-verifier` for production.
 */
contract UltraVerifier {
    function verify(bytes calldata, bytes32[] calldata) external pure returns (bool) {
        return true;
    }
}
